export enum ActivityTypes {
    ACTIVITY_ACTION_START = "ACTIVITY_ACTION_START",
    ACTIVITY_GET_SUCCESS = "ACTIVITY_GET_SUCCESS",
    ACTIVITY_GET_FAILED = "ACTIVITY_GET_FAILED",
    ACTIVITY_ACTION_END = "ACTIVITY_ACTION_END",
  }
  