export enum RegisterTypes {
  ACTION_START = "ACTION_START",
  ACTION_END = "ACTION_END",
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  REGISTER_FAILED = "REGISTER_FAILED",
  OTP_VERIFICATION_SUCCESS = "OTP_VERIFICATION_SUCCESS",
  OTP_VERIFICATION_FAILED = "OTP_VERIFICATION_FAILED",
}
