export enum NorificationTypes {
  NOTIFICATION_ACTION_START = "NOTIFICATION_ACTION_START",
  NOTIFICATION_GET_SUCCESS = "NOTIFICATION_GET_SUCCESS",
  NOTIFICATION_GET_FAILED = "NOTIFICATION_GET_FAILED",
  NOTIFICATION_ACTION_END = "NOTIFICATION_ACTION_END",
}
